import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, '..');

const toastDir   = join(root, 'frontend', 'search-toast');
const settingsDir = join(root, 'frontend', 'settings');

const toastCss   = readFileSync(join(toastDir, 'search-toast.css'), 'utf8');
const toastIcon  = readFileSync(join(toastDir, 'magnifier.svg'), 'utf8').trim();
const toastXIcon = readFileSync(join(toastDir, 'x.svg'), 'utf8').trim();
const toastOkIcon = readFileSync(join(toastDir, 'check.svg'), 'utf8').trim();
const settingsCss  = readFileSync(join(settingsDir, 'settings.css'), 'utf8');
const trashIcon    = readFileSync(join(settingsDir, 'trash.svg'), 'utf8').trim();
const libraryIcon  = readFileSync(join(settingsDir, 'library.svg'), 'utf8').trim();
const muteIcon = readFileSync(join(settingsDir, 'mute.svg'), 'utf8').trim();

function asTsLiteral(s) {
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

const frontendOut = join(root, 'frontend', '_assets.generated.ts');
const banner =
`// AUTO-GENERATED by scripts/build-assets.mjs — DO NOT EDIT BY HAND.
// Source: frontend/search-toast/*, frontend/settings/*
`;
const body =
`export const SEARCH_TOAST_CSS   = ${asTsLiteral(toastCss)};
export const SEARCH_TOAST_ICON  = ${asTsLiteral(toastIcon)};
export const SEARCH_TOAST_X     = ${asTsLiteral(toastXIcon)};
export const SEARCH_TOAST_CHECK = ${asTsLiteral(toastOkIcon)};

export const SETTINGS_CSS = ${asTsLiteral(settingsCss)};
export const SETTINGS_ICONS = {
  trash: ${asTsLiteral(trashIcon)},
  library: ${asTsLiteral(libraryIcon)},
  mute: ${asTsLiteral(muteIcon)},
};
`;

writeFileSync(frontendOut, banner + '\n' + body, 'utf8');
console.log(`[build-assets] wrote ${frontendOut} (css: ${toastCss.length} chars)`);
