import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, '..');

const welcomeDir = join(root, 'webkit', 'welcome');
const iconsDir   = join(welcomeDir, 'icons');
const outPath    = join(root, 'webkit', '_assets.generated.ts');

const welcomeCss  = readFileSync(join(welcomeDir, 'welcome.css'),  'utf8');
const welcomeHtml = readFileSync(join(welcomeDir, 'welcome.html'), 'utf8');

const ICON_NAMES = ['music', 'search', 'sparkles', 'zap', 'settings', 'x', 'play'];
const icons = Object.fromEntries(
  ICON_NAMES.map((name) => [name, readFileSync(join(iconsDir, `${name}.svg`), 'utf8').trim()]),
);

function asTsLiteral(s) {
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

const banner =
`// AUTO-GENERATED by scripts/build-assets.mjs — DO NOT EDIT BY HAND.
// Source: webkit/welcome/welcome.css, webkit/welcome/welcome.html, webkit/welcome/icons/*.svg
`;

const iconEntries = ICON_NAMES
  .map((name) => `  ${name}: ${asTsLiteral(icons[name])},`)
  .join('\n');

const body =
`export const WELCOME_CSS_TEMPLATE  = ${asTsLiteral(welcomeCss)};
export const WELCOME_HTML_TEMPLATE = ${asTsLiteral(welcomeHtml)};

export const WELCOME_ICONS = {
${iconEntries}
};
`;

writeFileSync(outPath, banner + '\n' + body, 'utf8');

console.log(
  `[build-assets] wrote ${outPath}`
  + ` (css: ${welcomeCss.length} chars, html: ${welcomeHtml.length} chars, icons: ${ICON_NAMES.length})`
);
