import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root      = resolve(__dirname, '..');

const frontendOut = resolve(root, 'frontend', '_assets.generated.ts');

// Keep the generated module tracked so clean checkouts do not depend on an
// asset pipeline. Native Steam components provide every UI visual.
writeFileSync(
  frontendOut,
  '// AUTO-GENERATED by scripts/build-assets.mjs — DO NOT EDIT BY HAND.\nexport const ASSET_GENERATION_VERSION = 2;\n',
  'utf8',
);
